services:
  - type: web
    name: anonchat-backend
    env: docker
    plan: free
    region: oregon
    dockerContext: ./anonchat-backend
    dockerfilePath: ./anonchat-backend/Dockerfile
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true

  - type: web
    name: anonchat-frontend
    env: docker
    plan: free
    region: oregon
    dockerContext: ./anonchat-frontend
    dockerfilePath: ./anonchat-frontend/Dockerfile
    envVars:
      - key: VITE_SIGNALING_URL
        value: https://anonchat-backend.onrender.com
    autoDeploy: true
